Checking if childFooter is set before trying to expand
There are cases where the childFooter is null and we're getting this error. So similar to what you have on collapse we should validate first.

ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'nativeElement' of null
TypeError: Cannot read property 'nativeElement' of null
    at IonicPullupComponent.expand (http://localhost/module-es2015.js:4817:49)